python code/train.py --experiment col_bedroom --test_model 1 --test True --test_epoch 24
python code/train.py --experiment col_church --test_model 1 --test True --test_epoch 24
python code/train.py --experiment denblind_bedroom --test_model 1 --test True --test_epoch 24
python code/train.py --experiment denblind_church --test_model 1 --test True --test_epoch 24
python code/train.py --experiment denblind_conference --test_model 1 --test True --test_epoch 24
python code/train.py --experiment inpcrop_bedroom --test_model 1 --test True --test_epoch 24
python code/train.py --experiment inpcrop_church --test_model 1 --test True --test_epoch 24
python code/train.py --experiment inpcrop_conference --test_model 1 --test True --test_epoch 24
python code/train.py --experiment inpvar_bedroom --test_model 1 --test True --test_epoch 24
python code/train.py --experiment inpvar_church --test_model 1 --test True --test_epoch 24
python code/train.py --experiment inpvar_conference --test_model 1 --test True --test_epoch 24